global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "influxdb_http_check"
    metrics_path: /probe
    params:
      module: [http_2xx_check]
      target: ["http://influxdb:8086"]
    static_configs:
      - targets:
          - "blackbox_exporter:9115"

  - job_name: "grafana_http_check"
    metrics_path: /probe
    params:
      module: [http_2xx_check]
      target: ["http://grafana:3000"]
    static_configs:
      - targets:
          - "blackbox_exporter:9115"

  - job_name: "vault_http_check"
    metrics_path: /probe
    params:
      module: [http_2xx_check]
      target: ["http://vault:8200"]
    static_configs:
      - targets:
          - "blackbox_exporter:9115"

  - job_name: "unleashweb_http_check"
    metrics_path: /probe
    params:
      module: [http_2xx_check]
      target: ["http://unleashweb:4242"]
    static_configs:
      - targets:
          - "blackbox_exporter:9115"

  - job_name: "unleashdb_http_check"
    metrics_path: /probe
    params:
      module: [http_2xx_check]
      target: ["http://unleashdb:5432"]
    static_configs:
      - targets:
          - "blackbox_exporter:9115"

  - job_name: "postgresql_unleashdb"
    params:
      auth_module: [unleash_db]
    static_configs:
      - targets:
          - "postgres_exporter_unleashdb:9187"
