modules:
  http_2xx_check:
    prober: http
    timeout: 5s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      valid_status_codes: [] # An empty list means any status code is OK.
      method: GET
